### ISSUE TITLE
[Bug] No Action or Hovering on Hire Me Button

### ISSUE THREAD

**Issue by mohammedshahid096** [Myself-Ikram/PortFolio#1]
**Describe the bug**
when ever the "Hire Me" Button is at bottom of the page, the hover or action is not performing, infact "it should hover and perform an action "

**To Reproduce**
Steps to reproduce the behaviour
1. Go to the About Section
2. Keep the Hire Me Button at bottom of the screen
3.  Hover or Click to the Button
4.  It will not hover nor on clicking the button no action takes places

**Expected Behaviour**
It should get hover or on clicking the button it should perform an action

**Screenshots**
![Screenshot 2023-08-02 201411](https://github.com/Myself-Ikram/MyPortfolio/assets/84904302/7763979c-cbeb-4063-bc27-3b56757b7520)

**Comment by Myself-Ikram** [comment]
Thanks for your concern.
You might try: 
1.Refreshing the browser
2.Check the network connectivity

Talking about the action of HIRE ME button, on clicking it will direct you to contact us page where you can contact through direct mail and even get in touch through LinkedIn,or any other social media accounts.
Note: only Facebook, LinkedIn and GitHub accounts are linked!

**Comment by Myself-Ikram** [comment]
If you are facing this same
1.use btn-outline-* for hovering effect from bootstrap library
2.mention contact us I'd in the href of anchor tag
Hope this helps!
